version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/DockerFile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
        - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
        - UPLOAD_FOLDER="./upload"
        - PORT=3001
    environment:
      - NODE_ENV=production
    volumes:
      - ./volume/upload:/app/upload
  web:
    build:
      context: .
      dockerfile: web/DockerFile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - PORT=3000
    environment:
      - NODE_ENV=production