version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/DockerFile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production