/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/swagger/all-json': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getSwaggerAll-json'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/project/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getProject'];
        put?: never;
        post: operations['postProject'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/project/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getProjectById'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/project/{id}/thumbnail': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getProjectByIdThumbnail'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/project/{id}/token': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getProjectByIdToken'];
        put?: never;
        /** Add a token to the project */
        post: operations['postProjectByIdToken'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/project/{id}/token/{tokenId}/buy': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['postProjectByIdTokenByTokenIdBuy'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/developer/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getDeveloper'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/developer/stats': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getDeveloperStats'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/payment/add': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['postPaymentAdd'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/payment/remove': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations['postPaymentRemove'];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations['getIndex'];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    'getSwaggerAll-json': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            developerId: string;
                            location: string;
                            name: string;
                            description: string;
                            createdAt: Record<string, never>;
                            updatedAt: Record<string, never>;
                            developer: string;
                        }[];
                    };
                    'multipart/form-data': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            developerId: string;
                            location: string;
                            name: string;
                            description: string;
                            createdAt: Record<string, never>;
                            updatedAt: Record<string, never>;
                            developer: string;
                        }[];
                    };
                    'text/plain': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            developerId: string;
                            location: string;
                            name: string;
                            description: string;
                            createdAt: Record<string, never>;
                            updatedAt: Record<string, never>;
                            developer: string;
                        }[];
                    };
                };
            };
        };
    };
    postProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    location: string;
                    name: string;
                    description?: string;
                    /**
                     * Format: binary
                     * @default File
                     */
                    thumbnail: string;
                };
                'multipart/form-data': {
                    location: string;
                    name: string;
                    description?: string;
                    /**
                     * Format: binary
                     * @default File
                     */
                    thumbnail: string;
                };
                'text/plain': {
                    location: string;
                    name: string;
                    description?: string;
                    /**
                     * Format: binary
                     * @default File
                     */
                    thumbnail: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProjectById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            developerId: string;
                            location: string;
                            name: string;
                            description: string;
                            createdAt: Record<string, never>;
                            updatedAt: Record<string, never>;
                        };
                    };
                    'multipart/form-data': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            developerId: string;
                            location: string;
                            name: string;
                            description: string;
                            createdAt: Record<string, never>;
                            updatedAt: Record<string, never>;
                        };
                    };
                    'text/plain': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            developerId: string;
                            location: string;
                            name: string;
                            description: string;
                            createdAt: Record<string, never>;
                            updatedAt: Record<string, never>;
                        };
                    };
                };
            };
        };
    };
    getProjectByIdThumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getProjectByIdToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            tokenId: number | null;
                            projectId: string;
                            name: string;
                            amount: string;
                            unsoldAmount: string;
                            pricePerToken: string;
                            startDate: string;
                            endDate: string;
                            createdAt: Record<string, never>;
                        }[];
                    };
                    'multipart/form-data': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            tokenId: number | null;
                            projectId: string;
                            name: string;
                            amount: string;
                            unsoldAmount: string;
                            pricePerToken: string;
                            startDate: string;
                            endDate: string;
                            createdAt: Record<string, never>;
                        }[];
                    };
                    'text/plain': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            id: string;
                            tokenId: number | null;
                            projectId: string;
                            name: string;
                            amount: string;
                            unsoldAmount: string;
                            pricePerToken: string;
                            startDate: string;
                            endDate: string;
                            createdAt: Record<string, never>;
                        }[];
                    };
                };
            };
        };
    };
    postProjectByIdToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    name: string;
                    amount: string;
                    pricePerToken?: string;
                    startDate: string;
                    endDate: string;
                };
                'multipart/form-data': {
                    name: string;
                    amount: string;
                    pricePerToken?: string;
                    startDate: string;
                    endDate: string;
                };
                'text/plain': {
                    name: string;
                    amount: string;
                    pricePerToken?: string;
                    startDate: string;
                    endDate: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    postProjectByIdTokenByTokenIdBuy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    amount: number;
                };
                'multipart/form-data': {
                    amount: number;
                };
                'text/plain': {
                    amount: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            transactionHash: string;
                        };
                    };
                    'multipart/form-data': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            transactionHash: string;
                        };
                    };
                    'text/plain': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            transactionHash: string;
                        };
                    };
                };
            };
        };
    };
    getDeveloper: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getDeveloperStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            totalCarbonOffset: number;
                            activeCredits: number;
                            retiredCredits: number;
                            totalProjects: number;
                        };
                    };
                    'multipart/form-data': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            totalCarbonOffset: number;
                            activeCredits: number;
                            retiredCredits: number;
                            totalProjects: number;
                        };
                    };
                    'text/plain': {
                        /** @constant */
                        status: 'ok';
                        data: {
                            totalCarbonOffset: number;
                            activeCredits: number;
                            retiredCredits: number;
                            totalProjects: number;
                        };
                    };
                };
            };
        };
    };
    postPaymentAdd: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    amount: number;
                };
                'multipart/form-data': {
                    amount: number;
                };
                'text/plain': {
                    amount: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @constant */
                        status: 'ok';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        status: 'ok';
                    };
                    'text/plain': {
                        /** @constant */
                        status: 'ok';
                    };
                };
            };
        };
    };
    postPaymentRemove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                'application/json': {
                    amount: number;
                };
                'multipart/form-data': {
                    amount: number;
                };
                'text/plain': {
                    amount: number;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    'application/json': {
                        /** @constant */
                        status: 'ok';
                    };
                    'multipart/form-data': {
                        /** @constant */
                        status: 'ok';
                    };
                    'text/plain': {
                        /** @constant */
                        status: 'ok';
                    };
                };
            };
        };
    };
    getIndex: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
