import type { Metadata } from "next";
import { Prompt } from 'next/font/google'
import "./globals.css";

const fontPrompt = Prompt({
  weight: ['400'],
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontPrompt.className} antialiased`}
      >
          {children}
      </body>
    </html>
  );
}
