FROM oven/bun:1 AS build

WORKDIR /app

# Cache packages
COPY package.json package.json
COPY bun.lock bun.lock

COPY /api/package.json ./api/package.json
COPY /web/package.json ./web/package.json
COPY /contracts/package.json ./contracts/package.json

RUN bun install

COPY /api ./api

WORKDIR /app/api

ENV NODE_ENV=production

RUN bun build \
	--compile \
	--minify-whitespace \
	--minify-syntax \
	--target bun \
	--outfile server \
	./src/app.ts

FROM gcr.io/distroless/base

WORKDIR /app

COPY --from=build /app/api/server server
COPY --from=build /app/api/src/contracts/artifacts ./src/contracts/artifacts

# Environment variables
ENV NODE_ENV=production
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}
ARG BETTER_AUTH_SECRET
ENV BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ARG WALLET_PRIVATE_KEY
ENV WALLET_PRIVATE_KEY=${WALLET_PRIVATE_KEY}
ARG CONTRACT_ADDRESS
ENV CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
ARG PORT
ENV PORT=${PORT}

CMD ["./server"]

EXPOSE ${PORT}